In [8]:
# pandas入门
import pandas as pd

from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [12]:
obj2['d']	=	6
obj2[['c',	'a',	'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2	>	0] 

d    6
b    7
c    3
dtype: int64

In [14]:
obj2	*	2 

d    12
b    14
a   -10
c     6
dtype: int64

In [2]:
import numpy as np

np.exp(obj2)

NameError: name 'obj2' is not defined

In [17]:
'b'	in	obj2 

True

In [18]:
'e'	in	obj2 

False

In [4]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [5]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [6]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [7]:
obj4 = pd.Series(sdata, index = states)

In [8]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [10]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [11]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [12]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [13]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj = pd.Series([4,7,-5,3])


In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada','Nevada','Nevada'],
'year': [2000,2001,2002,2001,2002,2003],
'pop': [1.5, 1.7, 3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [42]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [43]:
frame['debt']=16.5

In [44]:
frame

state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [45]:
frame['debt']=np.arange(6.)

In [46]:
frame

state  year  pop  debt
0    Ohio  2000  1.5   0.0
1    Ohio  2001  1.7   1.0
2    Ohio  2002  3.6   2.0
3  Nevada  2001  2.4   3.0
4  Nevada  2002  2.9   4.0
5  Nevada  2003  3.2   5.0

In [47]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [48]:
frame['debt']=val

In [49]:
frame

state  year  pop  debt
0    Ohio  2000  1.5   NaN
1    Ohio  2001  1.7   NaN
2    Ohio  2002  3.6   NaN
3  Nevada  2001  2.4   NaN
4  Nevada  2002  2.9   NaN
5  Nevada  2003  3.2   NaN

In [50]:
frame['eastern'] = frame.state == 'Ohio'
frame

state  year  pop  debt  eastern
0    Ohio  2000  1.5   NaN     True
1    Ohio  2001  1.7   NaN     True
2    Ohio  2002  3.6   NaN     True
3  Nevada  2001  2.4   NaN    False
4  Nevada  2002  2.9   NaN    False
5  Nevada  2003  3.2   NaN    False

In [51]:
del frame['eastern']

In [52]:
frame.columns

Index(['state', 'year', 'pop', 'debt'], dtype='object')

In [54]:
# 嵌套字典
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [55]:
frame3 = pd.DataFrame(pop)

In [57]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [58]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [61]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [63]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [66]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [67]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [69]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [70]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [71]:
index = obj.index

In [72]:
index

Index(['a', 'b', 'c'], dtype='object')

In [73]:
index[1:]

Index(['b', 'c'], dtype='object')

In [75]:
index[1] = 'd' #TypeError

TypeError: Index does not support mutable operations

In [80]:
import numpy as np

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [85]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [88]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [89]:
'Ohio' in frame3.columns

True

In [90]:
2003 in frame3.index

False

In [91]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [92]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [93]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [94]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [95]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [96]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [97]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [98]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [100]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [101]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','b','c'], columns=['Ohio', 'Texas', 'California'])

In [102]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [103]:
frame2 = frame.reindex(['a','b','c','d'])

In [104]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [105]:
states = ['Texas', 'Utah', 'California']

In [107]:
# 列可以用columns关键字重新索引
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [108]:
# 丢弃指定轴上的信息
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [109]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [110]:
new_obj = obj.drop('c')

In [111]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [113]:
data = pd.DataFrame(
    np.arange(16).reshape((4,4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four']
)

In [114]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data.T

Ohio  Colorado  Utah  New York
one       0         4     8        12
two       1         5     9        13
three     2         6    10        14
four      3         7    11        15

In [116]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [118]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [119]:
obj.drop('c', inplace=True)

In [120]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [121]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [122]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [123]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [124]:
obj['b']

1.0

In [125]:
obj[1]

1.0

In [126]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [128]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [129]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [130]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [131]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [132]:
obj['b':'c']=5

In [133]:
obj


a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [134]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [135]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [137]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [138]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [139]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [141]:
data[data<5]=0

In [142]:
# 用loc(轴标签)和iloc(整体索引)进行选取

In [143]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [144]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [145]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [146]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [147]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [148]:
# 整数索引
ser = pd.Series(np.arange(3.))

In [149]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [150]:
ser[-1]

KeyError: -1

In [151]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [152]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])

In [153]:
ser2[-1]

2.0

In [154]:
ser[:1]

0    0.0
dtype: float64

In [155]:
ser[:1]

0    0.0
dtype: float64

In [156]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [158]:
ser.iloc[:1]

0    0.0
dtype: float64

In [160]:
# 算数运算和数据对齐
s1 = pd.Series([7.3, -2.5, 3.5, 1.5], index=['a','c','d','e'])

In [161]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c','e','f','g'])

In [162]:
s1

a    7.3
c   -2.5
d    3.5
e    1.5
dtype: float64

In [163]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [164]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [165]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [166]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [167]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [168]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [169]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [170]:
df1 = pd.DataFrame({'A': [1,2]})
df2 = pd.DataFrame({'B': [3,4]})

In [171]:
df1

A
0  1
1  2

In [172]:
df2

B
0  3
1  4

In [173]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [174]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [175]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [176]:
df2.loc[1, 'b'] = np.nan

In [177]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [178]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [179]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [180]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [181]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [182]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [183]:
arr = np.arange(12.).reshape((3,4))

In [184]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [185]:
arr[0]

array([0., 1., 2., 3.])

In [186]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [187]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [188]:
series = frame.iloc[0]

In [189]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [190]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [191]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [192]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [193]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [194]:
series3 = frame['d']

In [195]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [196]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [197]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [200]:
# 函数应用和映射
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [198]:
np.abs(frame)

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [201]:
f = lambda x: x.max() - x.min()

In [202]:
frame.apply(f)

b    2.199261
d    2.711205
e    0.716893
dtype: float64

In [203]:
frame.apply(f, axis='columns')

Utah      0.962669
Ohio      1.716219
Texas     1.061403
Oregon    1.835531
dtype: float64

In [204]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [205]:
frame.apply(f)

b         d         e
min -0.956001 -1.375366 -1.216585
max  1.243260  1.335839 -0.499692

In [206]:
format = lambda x: '%.2f' % x

In [207]:
frame.applymap(format)

b      d      e
Utah    -0.96   0.01  -0.85
Ohio     1.01   0.52  -0.70
Texas   -0.31  -1.38  -1.22
Oregon   1.24   1.34  -0.50

In [208]:
frame['e'].map(format)

Utah      -0.85
Ohio      -0.70
Texas     -1.22
Oregon    -0.50
Name: e, dtype: object

In [209]:
# 排序与排名
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [210]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [211]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [212]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [214]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [215]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [218]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [219]:
obj = pd.Series([4, 7, -3, 2])

In [220]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [221]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [222]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [223]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0,1,0,1]})

In [224]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [225]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [226]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [227]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [228]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [229]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [230]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0,1,0,1], 'c':[-2, 5,8, -2.5]})

In [231]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [236]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [237]:
# 带有重复标签的轴索引
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [238]:
obj.index.is_unique

False

In [240]:
obj['a']

a    0
a    1
dtype: int64

In [241]:
obj['c']

4

In [242]:
df = pd.DataFrame(np.random.randn(4,3), index=['a', 'a', 'b', 'b'])

In [243]:
df

0         1         2
a -0.582923 -0.007821  1.183852
a  0.736818 -0.819700 -1.828183
b  0.138644  0.367267  0.058086
b  0.907676 -0.006325 -1.491529

In [245]:
df.loc['b']

0         1         2
b  0.138644  0.367267  0.058086
b  0.907676 -0.006325 -1.491529

In [247]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
index=['a','b','c','d'], columns=['one', 'two'])

In [248]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [251]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [252]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [253]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [254]:
df.idxmax()

one    b
two    d
dtype: object

In [255]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [257]:
df.describe() # 用于一次性产生多个汇总统计

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [258]:
obj = pd.Series(['a','a','b','c'] * 4)

In [261]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [2]:
import pandas_datareader.data as web

In [264]:
import datetime

In [267]:
import requests_cache

In [268]:
expire_after = datetime.timedelta(days=3)

In [270]:
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)

In [272]:
start = datetime.datetime(2010,1,1)

In [273]:
end = datetime.datetime(2013,1,27)

In [274]:
f = web.DataReader("F", 'yahoo', start, end, session=session)

In [277]:
f

High    Low   Open  Close       Volume  Adj Close
Date                                                          
2009-12-31  10.06   9.92  10.04  10.00   31253700.0   7.148519
2010-01-04  10.28  10.05  10.17  10.28   60855800.0   7.348678
2010-01-05  11.24  10.40  10.45  10.96  215620200.0   7.834775
2010-01-06  11.46  11.13  11.21  11.37  200070600.0   8.127864
2010-01-07  11.69  11.32  11.46  11.66  130201700.0   8.335171
...           ...    ...    ...    ...          ...        ...
2013-01-18  14.13  13.97  14.10  14.11   45716100.0  10.274902
2013-01-22  14.19  14.00  14.06  14.17   35467900.0  10.318596
2013-01-23  14.02  13.79  14.00  13.88   58122200.0  10.107416
2013-01-24  13.98  13.81  13.82  13.87   42532700.0  10.100135
2013-01-25  13.84  13.64  13.83  13.68   53405400.0   9.961775

[772 rows x 6 columns]

In [4]:
all_data = {ticker:	web.get_data_yahoo(ticker) for ticker in ['AAPL',	'IBM',	'MSFT',	'GOOG']}


In [10]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})

In [12]:
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

In [13]:
returns = price.pct_change()

In [14]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [15]:
returns['MSFT'].corr(returns['IBM'])

0.49976361144151166

In [16]:
returns['MSFT'].cov(returns['IBM'])

8.870655479703549e-05

In [17]:
returns.MSFT.cov(returns.IBM)

8.870655479703549e-05

In [18]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [19]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [23]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [24]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [25]:
volume

AAPL      GOOG       IBM      MSFT
Date                                               
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [26]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [28]:
uniques = obj.unique()

In [31]:
pd.array(['c', 'a', 'd', 'b'], dtype = object)

<PandasArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: object

In [32]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [33]:
pd.value_counts(obj.values, sort = False)

d    1
a    3
b    2
c    3
dtype: int64

In [34]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [36]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [37]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [41]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [44]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [48]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int32)

In [49]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
'Qu2': [2,3,1,2,3],
'Qu3': [1,5,2,4,4]})

In [50]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [51]:
result = data.apply(pd.value_counts).fillna(0)

In [52]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0